### ISSUE TITLE
SBT run gives ExceptionInInitializerError

### ISSUE THREAD

**Issue by jpbnetley** [jpbnetley/Mongo-csv-importer#11]
When doing `sbt run`, the following error is presented.
ExceptionInInitializerError
The log output:
```
[info] running Main
[error] (run-main-0) java.lang.ExceptionInInitializerError
[error] java.lang.ExceptionInInitializerError
[error]         at Main$.run(Main.scala:12)
[error]         at monix.eval.TaskApp$$anon$1.run(TaskApp.scala:94)
[error]         at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:67)
[error]         at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:37)
[error]         at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
[error]         at cats.effect.IOApp.main(IOApp.scala:67)
[error]         at cats.effect.IOApp.main$(IOApp.scala:66)
[error]         at monix.eval.TaskApp$$anon$1.main(TaskApp.scala:88)
[error]         at monix.eval.TaskApp.main(TaskApp.scala:96)
[error]         at monix.eval.TaskApp.main$(TaskApp.scala:86)
[error]         at Main$.main(Main.scala:9)
[error]         at Main.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] Caused by: java.util.NoSuchElementException
[error]         at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:608)
[error]         at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:606)
[error]         at scala.collection.immutable.HashMap.apply(HashMap.scala:131)
[error]         at Util.Database.Database$.<clinit>(Database.scala:57)
[error]         at Main$.run(Main.scala:12)
[error]         at monix.eval.TaskApp$$anon$1.run(TaskApp.scala:94)
[error]         at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:67)
[error]         at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:37)
[error]         at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
[error]         at cats.effect.IOApp.main(IOApp.scala:67)
[error]         at cats.effect.IOApp.main$(IOApp.scala:66)
[error]         at monix.eval.TaskApp$$anon$1.main(TaskApp.scala:88)
[error]         at monix.eval.TaskApp.main(TaskApp.scala:96)
[error]         at monix.eval.TaskApp.main$(TaskApp.scala:86)
[error]         at Main$.main(Main.scala:9)
[error]         at Main.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run 'last Compile / bgRun' for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 1 s, completed 14 Apr 2020, 23:47:33
```

At this stage I am not sure why this error is happening.

A workaround it to run the Main object, in the Main.scala file.

**Comment by jpbnetley** [comment]
This seems to be when sbt run is typed in the sbt shell.
Or when a Taks app us created, with the sbt shell option checked.

**Comment by jpbnetley** [comment]
I realised this happens when one of the environment variable was not defined.
The problem was the following: 
```
private val databaseName: String = sys.env("mongo_db_name")
```

and I fixed it by updating the error message:

```
private val databaseName: String = sys.env.get("mongo_db_name").fold(throw error("environment variables not set for db name"))(identity)
```
